#include "common/guid_def.h"
#include <Windows.h>
#include <msctf.h>
#include <cstdio>
#include <string>

using GetClassFn=HRESULT(STDAPICALLTYPE*)(REFCLSID,REFIID,void**);
class ReadSession final:public ITfEditSession{LONG ref_=1;ITfContext*c_;std::wstring*out_;public:ReadSession(ITfContext*c,std::wstring*o):c_(c),out_(o){c_->AddRef();}~ReadSession(){c_->Release();}HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void**p)override{if(!p)return E_INVALIDARG;*p=nullptr;if(id==IID_IUnknown||id==IID_ITfEditSession){*p=this;AddRef();return S_OK;}return E_NOINTERFACE;}ULONG STDMETHODCALLTYPE AddRef()override{return InterlockedIncrement(&ref_);}ULONG STDMETHODCALLTYPE Release()override{auto v=InterlockedDecrement(&ref_);if(!v)delete this;return v;}HRESULT STDMETHODCALLTYPE DoEditSession(TfEditCookie ec)override{ITfRange*r=nullptr;HRESULT h=c_->GetStart(ec,&r);if(FAILED(h))return h;r->ShiftEndToRange(ec,r,TF_ANCHOR_END);WCHAR b[512]{};ULONG n=0;h=r->GetText(ec,0,b,511,&n);r->Release();if(SUCCEEDED(h))out_->assign(b,n);return h;}};
static bool Send(ITfKeyEventSink*s,ITfContext*c,const char*text,WPARAM commit){for(const char*p=text;*p;++p){BOOL e=FALSE;if(FAILED(s->OnKeyDown(c,(WPARAM)toupper((unsigned char)*p),0,&e))||!e){std::fprintf(stderr,"key rejected: %c eaten=%d\n",*p,e);return false;}}BOOL e=FALSE;HRESULT h=s->OnKeyDown(c,commit,0,&e);if(FAILED(h)||!e)std::fprintf(stderr,"commit rejected: %lu hr=0x%08lx eaten=%d\n",(unsigned long)commit,(unsigned long)h,e);return SUCCEEDED(h)&&e;}
int wmain(int argc,wchar_t**argv){if(argc!=2)return 2;CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);ITfThreadMgr*tm=nullptr;TfClientId id=0;ITfDocumentMgr*doc=nullptr;ITfContext*ctx=nullptr;TfEditCookie cookie=0;ITfTextInputProcessorEx*tip=nullptr;ITfKeyEventSink*keys=nullptr;HMODULE dll=nullptr;int rc=1;
 HRESULT setup=CoCreateInstance(CLSID_TF_ThreadMgr,nullptr,CLSCTX_INPROC_SERVER,IID_ITfThreadMgr,(void**)&tm);if(FAILED(setup)){std::fprintf(stderr,"ThreadMgr 0x%08lx\n",(unsigned long)setup);goto done;}setup=tm->Activate(&id);if(FAILED(setup)){std::fprintf(stderr,"Activate 0x%08lx\n",(unsigned long)setup);goto done;}setup=tm->CreateDocumentMgr(&doc);if(FAILED(setup)){std::fprintf(stderr,"CreateDocumentMgr 0x%08lx\n",(unsigned long)setup);goto done;}setup=doc->CreateContext(id,0,nullptr,&ctx,&cookie);if(FAILED(setup)){std::fprintf(stderr,"CreateContext 0x%08lx\n",(unsigned long)setup);goto done;}if(FAILED(doc->Push(ctx))||FAILED(tm->SetFocus(doc))){std::fprintf(stderr,"document focus failed\n");goto done;}
 dll=LoadLibraryW(argv[1]);if(!dll){std::fprintf(stderr,"LoadLibrary %lu\n",GetLastError());goto done;}{auto get=(GetClassFn)GetProcAddress(dll,"DllGetClassObject");IClassFactory*f=nullptr;HRESULT h=get?get(CLSID_ShuruTextService,IID_IClassFactory,(void**)&f):E_POINTER;if(FAILED(h)){std::fprintf(stderr,"factory 0x%08lx\n",(unsigned long)h);goto done;}h=f->CreateInstance(nullptr,IID_ITfTextInputProcessorEx,(void**)&tip);f->Release();if(FAILED(h)){std::fprintf(stderr,"Create TIP 0x%08lx\n",(unsigned long)h);goto done;}h=tip->ActivateEx(tm,id,0);if(FAILED(h)){std::fprintf(stderr,"TIP ActivateEx 0x%08lx\n",(unsigned long)h);goto done;}h=tip->QueryInterface(IID_ITfKeyEventSink,(void**)&keys);if(FAILED(h)){std::fprintf(stderr,"key sink QI 0x%08lx\n",(unsigned long)h);goto done;}Sleep(2500);}
 // Real TSF composition through ITfThreadMgr/document/context and the production TIP.
 if(!Send(keys,ctx,"suixinshuru",'1')||!Send(keys,ctx,"shuru",VK_SPACE))goto done;{std::wstring text;auto*r=new ReadSession(ctx,&text);HRESULT session=E_FAIL;HRESULT h=ctx->RequestEditSession(id,r,TF_ES_SYNC|TF_ES_READ,&session);r->Release();if(FAILED(h)||FAILED(session)||text.find(L"随心")==std::wstring::npos||text.find(L"输入")==std::wstring::npos){std::fwprintf(stderr,L"unexpected TSF text: %ls\n",text.c_str());goto done;}}
 std::wprintf(L"real TSF thread/document/context composition E2E passed\n");rc=0;
done:if(keys)keys->Release();if(tip){tip->Deactivate();tip->Release();}if(doc)doc->Pop(TF_POPF_ALL);if(ctx)ctx->Release();if(doc)doc->Release();if(tm){tm->Deactivate();tm->Release();}if(dll)FreeLibrary(dll);CoUninitialize();return rc;}
