#!/usr/bin/env python3
"""Generate and validate the Facai Pinyin versioned lexicon manifest."""
from __future__ import annotations
import argparse, hashlib, json, re, struct, sys
from pathlib import Path

COMMENT = ("#", ";")
PINYIN = re.compile(r"^[a-z]+$")
ENGLISH = re.compile(r"^[A-Za-z][A-Za-z'-]*$")
DEFAULT_METADATA = {
    "base_dict.txt": {"source": "Rime Frost commit 2aedeea96c1468c1caa17cea01864419a11a4b26 selected dictionaries plus project custom_dict.txt; generated by scripts/build_frost_lexicon.py", "license": "GPL-3.0-only"},
    "char_dict.txt": {"source": "Rime Frost cn_dicts/8105.dict.yaml at commit 2aedeea96c1468c1caa17cea01864419a11a4b26; generated by scripts/build_frost_lexicon.py", "license": "GPL-3.0-only"},
    "en_dict.txt": {"source": "BlindingDark/rime-easy-en easy_en.dict.yaml commit 54a4a07289412efc54134092c0d945f895a71ed3; merged with the legacy project English lexicon by scripts/build_en_dict.py; see docs/lexicon-governance.md", "license": "LGPL-3.0-only (upstream repository); MIT attribution (ECDICT source)"},
    "base_dict.txt.bin": {"source": "validated derived cache of base_dict.txt", "license": "GPL-3.0-only"},
    "char_dict.txt.bin": {"source": "validated derived cache of char_dict.txt", "license": "GPL-3.0-only"},
    "rime-moqi-zh.gram": {
        "source": "gaboolic/rime-build-grammar release 1.0.0 asset rime-moqi-zh.gram; upstream SHA-256 35993085E9CE5D9722050BD548B807572EDCDD784ABF8079152091F8CD9BC731",
        "license": "NOASSERTION",
        "runtimeOptional": True,
    },
    "system_ngram.bin": {
        "source": "rime-ice cn_dicts/ext.dict.yaml and cn_dicts/tencent.dict.yaml commit 569ff3bc65dd4aec0a26b33c49c8bbdfa8b5fd57; generated by scripts/build_system_ngram.py",
        "license": "GPL-3.0-only",
    },
    "system_lexeme_prior.bin": {
        "source": "Rime Frost 8105/base dictionaries at commit 2aedeea96c1468c1caa17cea01864419a11a4b26; single/two-character prior generated by scripts/build_lexeme_prior.py",
        "license": "GPL-3.0-only",
    },
    "GPL-3.0.txt": {"source": "Rime Frost LICENSE at pinned commit", "license": "GPL-3.0-only"},
}

FILES = (
    ("base_dict.txt", "chinese"),
    ("char_dict.txt", "chinese"),
    ("en_dict.txt", "english"),
    ("base_dict.txt.bin", "binary-cache"),
    ("char_dict.txt.bin", "binary-cache"),
    ("rime-moqi-zh.gram", "grammar-model"),
    ("system_ngram.bin", "legacy-ngram-model"),
    ("system_lexeme_prior.bin", "binary-prior"),
    ("GPL-3.0.txt", "gpl-license"),
)

GRAMMAR_METADATA = struct.Struct("<32sIIi")
GRAMMAR_PREFIX = b"Rime::Grammar/"
GRAMMAR_OFFSET_FIELD = 40
GRAMMAR_MAX_UNITS = 100_000_000
NGRAM_HEADER = struct.Struct("<8sIII")
NGRAM_BIGRAM = struct.Struct("<II")
NGRAM_TRIGRAM = struct.Struct("<QI")
NGRAM_MAGIC = b"CSNGRM1\0"
NGRAM_VERSION = 1
NGRAM_MAX_BIGRAMS = 1_000_000
NGRAM_MAX_TRIGRAMS = 2_000_000
LEXEME_HEADER = struct.Struct("<8sII")
LEXEME_RECORD = struct.Struct("<HHI")
LEXEME_MAGIC = b"CSLXPR1\0"
LEXEME_VERSION = 1
LEXEME_MAX_RECORDS = 500_000
LEXEME_MAX_PINYIN_BYTES = 128
LEXEME_MAX_WORD_BYTES = 256

class ValidationError(Exception): pass

def rows(path: Path):
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        text = raw.strip()
        if text and not text.startswith(COMMENT):
            yield number, text.split("\t")

def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""): h.update(block)
    return h.hexdigest()

def is_bmp_chinese(value: int) -> bool:
    return 0x4E00 <= value <= 0x9FFF

def inspect_grammar_model(path: Path):
    errors = []
    file_size = path.stat().st_size
    with path.open("rb") as stream:
        metadata_bytes = stream.read(GRAMMAR_METADATA.size)
        if len(metadata_bytes) != GRAMMAR_METADATA.size:
            return 0, [f"{path.name}: truncated Grammar metadata"]
        format_name, _checksum, unit_count, relative_offset = (
            GRAMMAR_METADATA.unpack(metadata_bytes)
        )
        if not format_name.startswith(GRAMMAR_PREFIX) or b"\0" not in format_name:
            errors.append(f"{path.name}: invalid Grammar format")
        if unit_count < 256 or unit_count > GRAMMAR_MAX_UNITS:
            errors.append(f"{path.name}: invalid Grammar unit count {unit_count}")
        array_offset = GRAMMAR_OFFSET_FIELD + relative_offset
        if array_offset < GRAMMAR_METADATA.size or array_offset % 4 != 0:
            errors.append(f"{path.name}: invalid double-array offset {array_offset}")
        expected_size = array_offset + unit_count * 4
        if expected_size != file_size:
            errors.append(
                f"{path.name}: binary size {file_size} != expected {expected_size}"
            )
        if not errors:
            stream.seek(array_offset)
            root_bytes = stream.read(4)
            if len(root_bytes) != 4:
                errors.append(f"{path.name}: missing double-array root")
            else:
                root = struct.unpack("<I", root_bytes)[0]
                label = root & ((1 << 31) | 0xFF)
                has_leaf = ((root >> 8) & 1) != 0
                offset = (root >> 10) << ((root & (1 << 9)) >> 6)
                if label != 0 or has_leaf or offset == 0 or offset >= 512:
                    errors.append(f"{path.name}: invalid double-array root")
    return unit_count, errors

def inspect_legacy_ngram_model(path: Path):
    errors = []
    file_size = path.stat().st_size
    with path.open("rb") as stream:
        header_bytes = stream.read(NGRAM_HEADER.size)
        if len(header_bytes) != NGRAM_HEADER.size:
            return 0, [f"{path.name}: truncated n-gram header"]
        magic, version, bigram_count, trigram_count = NGRAM_HEADER.unpack(
            header_bytes
        )
        if magic != NGRAM_MAGIC:
            errors.append(f"{path.name}: invalid n-gram magic")
        if version != NGRAM_VERSION:
            errors.append(
                f"{path.name}: unsupported n-gram version {version}"
            )
        if bigram_count > NGRAM_MAX_BIGRAMS:
            errors.append(
                f"{path.name}: excessive bigram count {bigram_count}"
            )
        if trigram_count > NGRAM_MAX_TRIGRAMS:
            errors.append(
                f"{path.name}: excessive trigram count {trigram_count}"
            )

        expected_size = (
            NGRAM_HEADER.size
            + bigram_count * NGRAM_BIGRAM.size
            + trigram_count * NGRAM_TRIGRAM.size
        )
        if expected_size != file_size:
            errors.append(
                f"{path.name}: binary size {file_size} != expected {expected_size}"
            )
        if errors:
            return bigram_count + trigram_count, errors

        previous_key = -1
        for index in range(bigram_count):
            record = stream.read(NGRAM_BIGRAM.size)
            if len(record) != NGRAM_BIGRAM.size:
                errors.append(f"{path.name}: truncated bigram record {index}")
                break
            key, count = NGRAM_BIGRAM.unpack(record)
            first, second = key >> 16, key & 0xFFFF
            if key <= previous_key:
                errors.append(
                    f"{path.name}: bigram keys are not strictly increasing at {index}"
                )
            if count == 0:
                errors.append(f"{path.name}: zero bigram count at {index}")
            if not is_bmp_chinese(first) or not is_bmp_chinese(second):
                errors.append(f"{path.name}: non-Chinese bigram key at {index}")
            previous_key = key

        previous_key = -1
        for index in range(trigram_count):
            record = stream.read(NGRAM_TRIGRAM.size)
            if len(record) != NGRAM_TRIGRAM.size:
                errors.append(f"{path.name}: truncated trigram record {index}")
                break
            key, count = NGRAM_TRIGRAM.unpack(record)
            characters = ((key >> 32) & 0xFFFF, (key >> 16) & 0xFFFF,
                          key & 0xFFFF)
            if key <= previous_key:
                errors.append(
                    f"{path.name}: trigram keys are not strictly increasing at {index}"
                )
            if count == 0:
                errors.append(f"{path.name}: zero trigram count at {index}")
            if not all(is_bmp_chinese(value) for value in characters):
                errors.append(f"{path.name}: non-Chinese trigram key at {index}")
            previous_key = key

        if stream.read(1):
            errors.append(f"{path.name}: trailing bytes after n-gram records")
    return bigram_count + trigram_count, errors

def inspect_lexeme_prior(path: Path):
    errors = []
    with path.open("rb") as stream:
        header_bytes = stream.read(LEXEME_HEADER.size)
        if len(header_bytes) != LEXEME_HEADER.size:
            return 0, [f"{path.name}: truncated lexeme-prior header"]
        magic, version, record_count = LEXEME_HEADER.unpack(header_bytes)
        if magic != LEXEME_MAGIC:
            errors.append(f"{path.name}: invalid lexeme-prior magic")
        if version != LEXEME_VERSION:
            errors.append(f"{path.name}: unsupported lexeme-prior version {version}")
        if record_count > LEXEME_MAX_RECORDS:
            errors.append(f"{path.name}: excessive lexeme-prior count {record_count}")
        minimum_size = LEXEME_HEADER.size + record_count * LEXEME_RECORD.size
        if path.stat().st_size < minimum_size:
            errors.append(
                f"{path.name}: binary size {path.stat().st_size} < minimum {minimum_size}"
            )
        if errors:
            return record_count, errors

        previous_key = None
        for index in range(record_count):
            record = stream.read(LEXEME_RECORD.size)
            if len(record) != LEXEME_RECORD.size:
                errors.append(f"{path.name}: truncated lexeme-prior record {index}")
                break
            pinyin_size, word_size, score = LEXEME_RECORD.unpack(record)
            if not 0 < pinyin_size <= LEXEME_MAX_PINYIN_BYTES:
                errors.append(f"{path.name}: invalid pinyin length at {index}")
                break
            if not 0 < word_size <= LEXEME_MAX_WORD_BYTES:
                errors.append(f"{path.name}: invalid word length at {index}")
                break
            pinyin_bytes = stream.read(pinyin_size)
            word_bytes = stream.read(word_size)
            if len(pinyin_bytes) != pinyin_size or len(word_bytes) != word_size:
                errors.append(f"{path.name}: truncated lexeme-prior payload {index}")
                break
            try:
                pinyin = pinyin_bytes.decode("ascii")
                word = word_bytes.decode("utf-8")
            except UnicodeDecodeError:
                errors.append(f"{path.name}: invalid text encoding at {index}")
                break
            key = (pinyin, word)
            if not PINYIN.fullmatch(pinyin):
                errors.append(f"{path.name}: invalid pinyin key at {index}")
            if not word or not all(is_bmp_chinese(ord(char)) for char in word):
                errors.append(f"{path.name}: non-Chinese word key at {index}")
            if score == 0:
                errors.append(f"{path.name}: zero lexeme-prior score at {index}")
            if previous_key is not None and key <= previous_key:
                errors.append(
                    f"{path.name}: lexeme-prior keys are not strictly increasing at {index}"
                )
            previous_key = key

        if stream.read(1):
            errors.append(f"{path.name}: trailing bytes after lexeme-prior records")
    return record_count, errors

def inspect_file(path: Path, kind: str, min_frequency: int, max_frequency: int):
    if kind == "binary-cache":
        return 0, [] if path.stat().st_size > 80 else [f"{path.name}: binary cache is too small"]
    if kind == "grammar-model":
        return inspect_grammar_model(path)
    if kind == "legacy-ngram-model":
        return inspect_legacy_ngram_model(path)
    if kind == "binary-prior":
        return inspect_lexeme_prior(path)
    if kind == "gpl-license":
        text = path.read_text(encoding="utf-8", errors="strict")
        return 0, [] if "GNU GENERAL PUBLIC LICENSE" in text and len(text) > 30000 else [f"{path.name}: invalid GPL text"]
    errors, seen, count = [], {}, 0
    for number, fields in rows(path):
        count += 1
        expected = 3 if kind == "chinese" else 2
        if len(fields) not in ((2, 3) if kind == "english" else (expected,)):
            errors.append(f"{path.name}:{number}: expected {expected} tab-separated columns, got {len(fields)}")
            continue
        fields = [x.strip() for x in fields]
        if kind == "chinese":
            pinyin, word, frequency = fields
            if not PINYIN.fullmatch(pinyin): errors.append(f"{path.name}:{number}: invalid pinyin {pinyin!r}")
            if not word: errors.append(f"{path.name}:{number}: empty word")
            key = (pinyin, word)
        else:
            if kind == "english" and len(fields) == 3:
                lookup_key, display_word, frequency = fields
                if not re.fullmatch(r"^[a-z]+$", lookup_key):
                    errors.append(f"{path.name}:{number}: invalid English lookup key {lookup_key!r}")
                if not ENGLISH.fullmatch(display_word):
                    errors.append(f"{path.name}:{number}: invalid English display word {display_word!r}")
                key = lookup_key
                if lookup_key != lookup_key.lower():
                    errors.append(f"{path.name}:{number}: English lookup key must be lowercase")
            else:
                word, frequency = fields
                if not ENGLISH.fullmatch(word): errors.append(f"{path.name}:{number}: invalid English word {word!r}")
                key = word.lower()
        try:
            value = int(frequency)
            if value < min_frequency or value > max_frequency:
                errors.append(f"{path.name}:{number}: frequency {value} outside [{min_frequency}, {max_frequency}]")
        except ValueError:
            errors.append(f"{path.name}:{number}: invalid integer frequency {frequency!r}")
        if key in seen: errors.append(f"{path.name}:{number}: exact duplicate of line {seen[key]}: {key!r}")
        else: seen[key] = number
    return count, errors

def build(directory: Path, package_id: str, version: str, schema: str, min_frequency: int, max_frequency: int):
    files, errors = [], []
    for name, kind in FILES:
        path = directory / name
        if not path.is_file(): errors.append(f"missing required file: {name}"); continue
        count, file_errors = inspect_file(path, kind, min_frequency, max_frequency)
        errors.extend(file_errors)
        files.append({
            "path": name,
            "kind": kind,
            **DEFAULT_METADATA[name],
            "entries": count,
            "size": path.stat().st_size,
            "sha256": sha256(path),
        })
    if errors: raise ValidationError("\n".join(errors))
    return {"packageId": package_id, "schemaVersion": schema, "version": version,
            "frequencyPolicy": {"min": min_frequency, "max": max_frequency}, "files": files}

def validate(directory: Path, manifest_path: Path, min_override, max_override):
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    for field in ("packageId", "schemaVersion", "version", "files"):
        if field not in manifest: raise ValidationError(f"manifest missing {field}")
    policy = manifest.get("frequencyPolicy", {})
    low = policy.get("min", 0) if min_override is None else min_override
    high = policy.get("max", 50_000_000) if max_override is None else max_override
    errors = []
    expected = {item["path"]: item for item in manifest["files"]}
    for name, kind in FILES:
        item, path = expected.get(name), directory / name
        if not item: errors.append(f"manifest missing file record: {name}"); continue
        for field in ("source", "license", "entries", "size", "sha256"):
            if field not in item or item[field] in (None, ""): errors.append(f"{name}: missing metadata {field}")
        if not path.is_file(): errors.append(f"missing required file: {name}"); continue
        count, file_errors = inspect_file(path, kind, int(low), int(high)); errors.extend(file_errors)
        if count != item.get("entries"): errors.append(f"{name}: entry count {count} != manifest {item.get('entries')}")
        if path.stat().st_size != item.get("size"): errors.append(f"{name}: size mismatch")
        digest = sha256(path)
        if digest.lower() != str(item.get("sha256", "")).lower(): errors.append(f"{name}: SHA-256 mismatch")
    if errors: raise ValidationError("\n".join(errors))
    return manifest

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "validate")); parser.add_argument("--dir", default="data/lexicon")
    parser.add_argument("--manifest", default="data/lexicon/manifest.json"); parser.add_argument("--package-id", default="caishen-pinyin-frost-moqi")
    parser.add_argument("--version", default="2.0.1"); parser.add_argument("--schema", default="2")
    parser.add_argument("--min-frequency", type=int); parser.add_argument("--max-frequency", type=int)
    args = parser.parse_args(); directory, manifest_path = Path(args.dir), Path(args.manifest)
    try:
        if args.command == "generate":
            result = build(directory, args.package_id, args.version, args.schema,
                           0 if args.min_frequency is None else args.min_frequency,
                           50_000_000 if args.max_frequency is None else args.max_frequency)
            manifest_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            print(f"generated {manifest_path} ({sum(x['entries'] for x in result['files'])} entries)")
        else:
            result = validate(directory, manifest_path, args.min_frequency, args.max_frequency)
            print(f"valid lexicon package {result['packageId']} {result['version']}")
        return 0
    except (OSError, ValueError, json.JSONDecodeError, ValidationError) as exc:
        print(f"LEXICON_VALIDATION_ERROR: {exc}", file=sys.stderr); return 2
if __name__ == "__main__": sys.exit(main())
